export const CAR_MAKES: Record<string, string[]> = {
  'Abarth': ['124 Spider', '500', 'Punto'],
  'Acura': ['ILX', 'MDX', 'RDX', 'TLX', 'NSX', 'Integra', 'RLX'],
  'Aixam': ['City', 'Coupe', 'Scouty'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale', 'Spider', 'Giulietta', 'Mito', '159', 'Brera', 'GT'],
  'Alpine': ['A110', 'A310', 'A610'],
  'Aston Martin': ['DB11', 'DB12', 'DBS', 'Vantage', 'DBX', 'Valhalla', 'Valkyrie', 'Rapide', 'Vanquish'],
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'Q4 e-tron', 'Q6 e-tron', 'R8', 'TT', 'RS3', 'RS6', 'S3', 'S4'],
  'BAW': ['Tonik', 'Beijing 3', 'X5', 'X7'],
  'Bentley': ['Bentayga', 'Continental GT', 'Flying Spur', 'Mulsanne', 'Azure'],
  'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'XM', 'i3', 'i4', 'i5', 'i7', 'iX', 'iX1', 'iX3', 'Z4', 'M2', 'M3', 'M4', 'M5', 'M8'],
  'Brilliance': ['H230', 'H530', 'V3', 'V5'],
  'Bugatti': ['Chiron', 'Veyron', 'Divo'],
  'Buick': ['Enclave', 'Encore', 'Envision', 'LaCrosse', 'Regal', 'Verano', 'LeSabre', 'Park Avenue'],
  'BYD': ['Atto 3', 'Seal', 'Dolphin', 'Han', 'Tang', 'Yuan Plus', 'Seagull', 'Song', 'Qin'],
  'Cadillac': ['CT4', 'CT5', 'CT6', 'Escalade', 'XT4', 'XT5', 'XT6', 'Lyriq', 'Celestiq', 'DeVille', 'SRX', 'ATS'],
  'Caterham': ['Seven', 'Seven 170', 'Seven 420'],
  'Changhe': ['Freedom', 'Ideal'],
  'Chery': ['Tiggo 2', 'Tiggo 4', 'Tiggo 7', 'Tiggo 8', 'Arrizo 5', 'Arrizo 8', 'eQ1', 'OMODA 5'],
  'Chevrolet': ['Blazer', 'Camaro', 'Captiva', 'Colorado', 'Corvette', 'Cruze', 'Equinox', 'Impala', 'Malibu', 'Silverado', 'Spark', 'Suburban', 'Tahoe', 'TrailBlazer', 'Traverse', 'Trax', 'Aveo', 'Lacetti', 'Niva', 'Cobalt', 'Volt', 'Bolt EV'],
  'Chrysler': ['300', 'Pacifica', 'Voyager', 'Aspen', 'Crossfire', 'PT Cruiser', 'Sebring', 'Town & Country'],
  'Citroen': ['C1', 'C3', 'C4', 'C5', 'C5 Aircross', 'C6', 'Berlingo', 'Jumpy', 'Spacetourer', 'Ami', 'DS3', 'DS4', 'DS5', 'Xsara', 'Saxo'],
  'Cupra': ['Born', 'Formentor', 'Leon', 'Ateca', 'Tavascan'],
  'Dacia': ['Duster', 'Sandero', 'Logan', 'Spring', 'Lodgy', 'Dokker', 'Jogger'],
  'Daewoo': ['Lanos', 'Nexia', 'Matiz', 'Leganza', 'Espero', 'Nubira', 'Kalos', 'Magnus', 'Tico', 'Damas'],
  'Daihatsu': ['Charade', 'Cuore', 'Move', 'Sirion', 'Terios', 'Mira', 'Applause'],
  'Datsun': ['mi-DO', 'on-DO', 'GO', 'GO+'],
  'Dodge': ['Charger', 'Challenger', 'Durango', 'Grand Caravan', 'Journey', 'Viper', 'Caliber', 'Neon', 'Avenger', 'Magnum', 'Ram'],
  'DS': ['DS 3', 'DS 4', 'DS 5', 'DS 7', 'DS 9'],
  'FAW': ['Bestune', 'Besturn', 'X40', 'T77', 'V5'],
  'Ferrari': ['296 GTB', '296 GTS', '812 Superfast', 'F8 Tributo', 'SF90 Stradale', 'Purosangue', 'Roma', 'Portofino', '458', '488', 'LaFerrari', 'F40', 'Enzo', 'California'],
  'Fiat': ['500', '500X', '500L', 'Panda', 'Tipo', 'Punto', 'Doblo', 'Ducato', 'Fiorino', 'Scudo', 'Bravo', 'Stilo', 'Croma', 'Multipla', 'Uno', 'Palio', '124 Spider'],
  'Ford': ['Focus', 'Fiesta', 'Kuga', 'Explorer', 'Explorer EV', 'Mustang', 'Mustang Mach-E', 'Transit', 'Ranger', 'EcoSport', 'Edge', 'Escape', 'Expedition', 'F-150', 'F-250', 'Galaxy', 'Mondeo', 'Tourneo', 'Puma', 'Bronco', 'Capri', 'C-Max', 'S-Max', 'Fusion', 'Taurus'],
  'Forthing': ['T5', 'M7', 'S50'],
  'Foton': ['Tunland', 'Sauvana', 'Midi', 'View'],
  'Geely': ['Coolray', 'Monjaro', 'Tugella', 'Emgrand', 'Atlas', 'Geometry A', 'Geometry C', 'Xingyue', 'Binrui', 'Boyue', 'Preface', 'Icon'],
  'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80', 'GV90'],
  'GMC': ['Sierra', 'Yukon', 'Terrain', 'Acadia', 'Canyon', 'Hummer EV'],
  'Great Wall': ['Haval H6', 'Haval H2', 'Haval Jolion', 'Haval Dargo', 'Haval F7', 'Wingle 5', 'Wingle 7', 'Poer', 'Ora'],
  'Haval': ['H6', 'Jolion', 'Dargo', 'F7', 'H9', 'M6', 'H2', 'H4'],
  'Honda': ['Civic', 'Accord', 'CR-V', 'HR-V', 'Pilot', 'Fit', 'City', 'Jazz', 'Odyssey', 'Ridgeline', 'Passport', 'Insight', 'NSX', 'S2000', 'Element', 'Prelude', 'Integra'],
  'Hummer': ['H1', 'H2', 'H3', 'EV'],
  'Hyundai': ['Elantra', 'Santa Fe', 'Tucson', 'Palisade', 'Sonata', 'Ioniq 5', 'Ioniq 6', 'Ioniq 9', 'Kona', 'Creta', 'Solaris', 'Accent', 'Getz', 'Grandeur', 'Genesis', 'i10', 'i20', 'i30', 'i40', 'Santa Cruz', 'Staria', 'Veloster', 'Tucson N'],
  'Infiniti': ['Q50', 'QX50', 'QX60', 'Q60', 'QX80', 'FX35', 'FX37', 'M37', 'EX35'],
  'Iran Khodro': ['Samand', 'Runna', 'Dena', 'Soren', 'Peugeot Pars'],
  'Isuzu': ['D-Max', 'MU-X', 'Trooper', 'Rodeo', 'Axiom', 'VehiCross', 'KB Pikap', 'N-Series'],
  'JAC': ['J7', 'JS4', 'JS6', 'JS8', 'S3', 'S7', 'T6', 'T8'],
  'Jaguar': ['F-PACE', 'E-PACE', 'I-PACE', 'XE', 'XF', 'XJ', 'F-TYPE', 'X-Type', 'S-Type', 'XK'],
  'Jeep': ['Grand Cherokee', 'Wrangler', 'Compass', 'Cherokee', 'Renegade', 'Gladiator', 'Liberty', 'Patriot', 'Commander', 'Avenger'],
  'Jetour': ['X70', 'X90', 'X95', 'Dashing'],
  'Kia': ['Sportage', 'Sorento', 'Rio', 'K5', 'EV6', 'EV9', 'Telluride', 'Soul', 'Stinger', 'Ceed', 'Cerato', 'Forte', 'Niro', 'Picanto', 'Mohave', 'Carnival', 'Seltos', 'Optima', 'Sephia'],
  'Koenigsegg': ['Agera', 'Jesko', 'Regera', 'Gemera', 'CCX'],
  'Lada': ['Granta', 'Vesta', 'Niva', 'Largus', 'Priora', 'Kalina', 'X-Ray', '2107', '2106', '2114', '2115', 'Largus Cross', 'Vesta SW Cross', 'e-Largus'],
  'Lamborghini': ['Urus', 'Huracan', 'Aventador', 'Revuelto', 'Gallardo', 'Murcielago', 'Countach', 'Diablo', 'Miura'],
  'Lancia': ['Ypsilon', 'Delta', 'Thesis', 'Musa', 'Phedra'],
  'Land Rover': ['Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar', 'Discovery', 'Discovery Sport', 'Defender', 'Freelander'],
  'Lexus': ['IS', 'ES', 'GS', 'LS', 'NX', 'RX', 'UX', 'LX', 'GX', 'RC', 'LC', 'RZ', 'LM'],
  'Lifan': ['Solano', 'X60', 'X70', 'Smily', 'Breez'],
  'Lincoln': ['Navigator', 'Aviator', 'Corsair', 'Nautilus', 'Continental', 'MKZ', 'MKC', 'MKX', 'Town Car'],
  'Lotus': ['Emira', 'Eletre', 'Evija', 'Exige', 'Elise', 'Evora', 'Esprit', 'Emeya'],
  'Lucid': ['Air', 'Gravity'],
  'Luxgen': ['URX', 'U6', 'M7'],
  'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'Grecale', 'MC20', 'GranTurismo', 'GranCabrio', '3200 GT'],
  'Mazda': ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-60', 'CX-90', 'MX-5', 'RX-8', 'RX-7', 'MX-30', 'BT-50', '323', '626', 'Premacy'],
  'McLaren': ['Artura', '750S', 'GT', 'Senna', 'Speedtail', 'P1', '720S', '600LT', '570S'],
  'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'EQV', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'S-Class', 'SL', 'SLC', 'V-Class', 'AMG GT', 'Sprinter', 'Vito', 'Citan', 'ML', 'GLK', 'CLK', 'SLK', '190'],
  'Mercury': ['Grand Marquis', 'Mariner', 'Milan', 'Mountaineer', 'Sable'],
  'MG': ['MG3', 'MG4', 'MG5', 'MG6', 'MG ZS', 'MG HS', 'MG Marvel R', 'MG Cyberster', 'MG Hector', 'MG RX8', 'TF'],
  'Microcar': ['M.Go', 'M.8', 'Duke'],
  'Mini': ['Cooper', 'Cooper S', 'Countryman', 'Clubman', 'Convertible', 'Paceman', 'Coupe', 'Roadster', 'Aceman', 'John Cooper Works'],
  'Mitsubishi': ['Outlander', 'Pajero', 'L200', 'ASX', 'Eclipse Cross', 'Lancer', 'Mirage', 'Space Star', 'Montero', 'Galant', 'Colt', 'Delica', 'Carisma', 'Sigma'],
  'Morgan': ['Plus Four', 'Plus Six', 'Super 3'],
  'Moskvich': ['3', '6', '2140', '412', '408', 'Aleko'],
  'NIO': ['ES6', 'ES8', 'ET5', 'ET7', 'EC6', 'EL6', 'EL7', 'EL8'],
  'Nissan': ['Altima', 'Qashqai', 'X-Trail', 'Patrol', 'Leaf', 'Ariya', 'Navara', 'Sentra', 'Versa', 'Juke', 'Kicks', 'Murano', 'Pathfinder', 'Armada', 'Frontier', 'Micra', 'Almera', 'Teana', 'Skyline', 'GT-R', '350Z', '370Z', 'Note', 'Cube', 'Terrano', 'Maxima', 'Primera', 'Sunny'],
  'Oldsmobile': ['Alero', 'Aurora', 'Bravada', 'Cutlass', 'Silhouette'],
  'Opel': ['Astra', 'Corsa', 'Mokka', 'Crossland', 'Grandland', 'Insignia', 'Zafira', 'Vivaro', 'Combo', 'Karl', 'Adam', 'Cascada', 'Meriva', 'Antara', 'Speedster', 'GT', 'Calibra', 'Omega', 'Vectra', 'Signum', 'Frontera', 'Monterey', 'Senator', 'Rekord', 'Kadett', 'Ascona', 'Manta', 'Diplomat', 'Commodore', 'Kapitan', 'Olympia', 'Blitz'],
  'Ora': ['Good Cat', 'Funky Cat', 'iQ', 'R1'],
  'Pagani': ['Huayra', 'Zonda', 'Utopia'],
  'Peugeot': ['208', '308', '508', '2008', '3008', '5008', 'Rifter', 'Traveller', 'Partner', 'Expert', 'Boxer', 'e-208', 'e-308', 'e-2008', '408', 'RCZ', '607', '407', '307', '206', '106', '605', '405', '505', '504'],
  'Pininfarina': ['Battista'],
  'Plymouth': ['Barracuda', 'Road Runner', 'GTX', 'Fury', 'Valiant', 'Duster', 'Satellite', 'Belvedere', 'Savoy', 'Suburban'],
  'Polestar': ['1', '2', '3', '4'],
  'Pontiac': ['Firebird', 'GTO', 'Trans Am', 'Grand Prix', 'Bonneville', 'Solstice', 'Vibe', 'Montana', 'Aztek', 'Fiero', 'Sunfire', 'Grand Am'],
  'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', 'Cayman', 'Boxster', '918 Spyder', 'Carrera GT', '718', 'Panamera Turbo'],
  'Proton': ['Persona', 'Saga', 'Waja', 'Wira', 'Perdana', 'Satria', 'Exora', 'X70', 'X50'],
  'RAM': ['1500', '2500', '3500', 'ProMaster', 'ProMaster City', 'Chassis Cab'],
  'Ravon': ['Gentra', 'R2', 'R4', 'Nexia', 'Matiz', 'Cobalt', 'Spark'],
  'Renault': ['Clio', 'Megane', 'Captur', 'Arkana', 'Duster', 'Koleos', 'Talisman', 'Zoe', 'Twingo', 'Scenic', 'Espace', 'Kadjar', 'Austral', 'Rafale', 'Master', 'Trafic', 'Kangoo', 'Laguna', 'Latitude', 'Fluence', 'Sandero', 'Logan', 'Symbol', 'Thalia', 'Modus', 'Avantime', 'Vel Satis', 'Safrane', '25', '21', '19', '5', '4'],
  'Rimac': ['Nevera', 'Concept One', 'Concept Two'],
  'Rivian': ['R1T', 'R1S', 'R2', 'R3'],
  'Rolls-Royce': ['Phantom', 'Ghost', 'Wraith', 'Dawn', 'Cullinan', 'Spectre', 'Silver Shadow', 'Silver Cloud', 'Corniche', 'Camargue'],
  'Rover': ['75', '45', '25', 'Streetwise', '200', '400', '600', '800', 'Mini', 'Metro', 'Maestro', 'Montego', 'SD1', 'P6', 'P5'],
  'Saab': ['9-3', '9-5', '900', '9000', '9-4X', '9-2X', 'Sonett', '96', '99', '900 Turbo'],
  'SAIC': ['Maxus', 'RX5', 'i5', 'i6'],
  'Saturn': ['S-Series', 'L-Series', 'Ion', 'Vue', 'Relay', 'Outlook', 'Aura', 'Sky'],
  'Scion': ['xA', 'xB', 'tC', 'xD', 'FR-S', 'iQ', 'iA', 'iM'],
  'Seat': ['Leon', 'Ibiza', 'Arona', 'Ateca', 'Tarraco', 'Alhambra', 'Mii', 'Toledo', 'Altea', 'Exeo', 'Malaga', 'Ronda', 'Fura'],
  'Skoda': ['Octavia', 'Superb', 'Kodiaq', 'Karoq', 'Kamiq', 'Fabia', 'Scala', 'Enyaq', 'Enyaq Coupe', 'Citigo', 'Rapid', 'Yeti', 'Roomster', 'Praktik', 'Felicia', 'Favorit', '105', '120', '130'],
  'Smart': ['Fortwo', 'Forfour', 'Roadster', 'Crossblade', 'EQ Fortwo', 'EQ Forfour', '#1'],
  'SsangYong': ['Korando', 'Tivoli', 'Rexton', 'Musso', 'Kyron', 'Actyon', 'Stavic', 'Chairman', 'Rodius'],
  'Subaru': ['Outback', 'Forester', 'Impreza', 'Legacy', 'WRX', 'BRZ', 'Crosstrek', 'XV', 'Solterra', 'Baja', 'SVX', 'XT', 'Justy', 'Leone', 'Alcyone', 'Tribeca', 'Ascent', 'Levorg'],
  'Suzuki': ['Swift', 'Vitara', 'S-Cross', 'Jimny', 'Baleno', 'Celerio', 'Ignis', 'Splash', 'Alto', 'Wagon R', 'Grand Vitara', 'Samurai', 'SJ', 'Cappuccino', 'Esteem', 'Kizashi', 'XL7', 'Across', 'Swace'],
  'TagAZ': ['Tager', 'Vortex Tingo', 'Aquila', 'Partner', 'C30', 'Road Partner'],
  'Tata': ['Safari', 'Harrier', 'Nexon', 'Altroz', 'Punch', 'Tiago', 'Tigor', 'Curvv', 'Indica', 'Indigo', 'Sumo', 'Xenon', 'Ace', 'Nano'],
  'Tesla': ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck', 'Roadster', 'Semi'],
  'Toyota': ['Camry', 'Corolla', 'RAV4', 'Land Cruiser', 'Prado', 'Highlander', 'C-HR', 'Yaris', 'Yaris Cross', 'Hilux', 'Tacoma', 'Tundra', '4Runner', 'Sequoia', 'Sienna', 'Avalon', 'Mirai', 'Supra', 'GR86', 'GR Yaris', 'GR Corolla', 'bZ4X', 'Prius', 'Celica', 'MR2', 'Starlet', 'Tercel', 'Crown', 'Mark II', 'Chaser', 'Soarer', 'Ae86', 'FJ Cruiser', 'Fortuner', 'Innova', 'Vios', 'Wish', 'Rush', 'Avanza'],
  'Trabant': ['601', 'P50', 'P60', '1.1'],
  'Triumph': ['TR6', 'TR7', 'TR8', 'Spitfire', 'GT6', 'Herald', 'Vitesse', 'Dolomite', 'Toledo', 'Stag', '2000', '2500', 'Acclaim'],
  'UAZ': ['Patriot', 'Hunter', 'Bukhanka', '469', 'Pickup', 'Cargo', 'SGR', 'Simba', 'TIGER', 'Prof'],
  'Vauxhall': ['Astra', 'Corsa', 'Mokka', 'Crossland', 'Grandland', 'Insignia', 'Vivaro', 'Combo', 'Zafira', 'Adam', 'Meriva'],
  'VinFast': ['VF e34', 'VF 5', 'VF 6', 'VF 7', 'VF 8', 'VF 9', 'Lux A2.0', 'Lux SA2.0', 'Fadil', 'President'],
  'Volkswagen': ['Golf', 'Passat', 'Tiguan', 'T-Roc', 'T-Cross', 'Taigo', 'ID.3', 'ID.4', 'ID.5', 'ID.7', 'ID.Buzz', 'Polo', 'Lavida', 'Jetta', 'Beetle', 'Scirocco', 'Corrado', 'Phaeton', 'Touareg', 'Amarok', 'Caddy', 'Multivan', 'Caravelle', 'Transporter', 'Crafter', 'LT', 'Kaefer', 'Karmann Ghia', 'Type 3', 'Type 4', '181', 'Iltis'],
  'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'S90', 'V60', 'V90', 'C40', 'EX30', 'EX90', 'EM90', 'S40', 'V40', 'S80', 'V70', 'XC70', 'C30', 'C70', '850', '740', '240', 'Amazon', 'Duett', 'PV', 'P1800'],
  'Vortex': ['Tingo', 'Corda', 'Estina'],
  'Voyah': ['Free', 'Dream', 'Passion', 'Courage'],
  'Wartburg': ['353', '1.3', '311', '312'],
  'Wuling': ['Mini EV', 'Bingo', 'Air EV', 'Confero', 'Cortez', 'Almaz', 'Formo', 'Carry', 'Sunshine', 'Hongguang'],
  'Xiaomi': ['SU7'],
  'XPeng': ['G3', 'G6', 'G9', 'P5', 'P7', 'X9'],
  'Zaporozhets': ['ZAZ 965', 'ZAZ 966', 'ZAZ 968', 'ZAZ 969', 'Tavria', 'Slavuta', 'Sens', 'Lanos', 'Vida', 'Chance', 'Forza'],
  'Zeekr': ['001', '007', '009', 'X', 'MIX', '7X'],
  'Zotye': ['T600', 'Z300', 'SR9', 'Coupa'],
};

// Real heavy-duty truck manufacturers — the general car list above has no
// dedicated commercial-truck brands at all (KAMAZ, Scania, Volvo Trucks,
// etc.), which matters for an app built for truckers.
export const TRUCK_MAKES: Record<string, string[]> = {
  'KAMAZ': ['4308', '5320', '5490', '5490 NEO', '54901', '65115', '65225', '43118', '6520'],
  'MAZ': ['5440', '5340', '6312', '6430', '533603', '4370 Zubrenok'],
  'Ural': ['4320', '5557', 'NEXT', '6370', '43206'],
  'KrAZ': ['6322', '65055', '6510', '5233'],
  'ZIL': ['131', '130', '4331', '5301 Bychok'],
  'GAZ': ['GAZon Next', 'Sadko', 'Valdai', '3309', '53'],
  'Volvo Trucks': ['FH', 'FH16', 'FM', 'FMX', 'FE', 'FL', 'VNL'],
  'Scania': ['R-series', 'S-series', 'G-series', 'P-series', 'L-series'],
  'MAN': ['TGX', 'TGS', 'TGM', 'TGL', 'TGE'],
  'DAF': ['XF', 'XG', 'XG+', 'CF', 'LF'],
  'Iveco': ['S-Way', 'Stralis', 'Trakker', 'Eurocargo', 'Daily'],
  'Renault Trucks': ['T', 'T High', 'C', 'K', 'D'],
  'Mercedes-Benz Trucks': ['Actros', 'Arocs', 'Atego', 'Axor', 'Econic'],
  'Freightliner': ['Cascadia', 'Columbia', 'Coronado', 'M2 106', '114SD'],
  'Kenworth': ['T680', 'T880', 'W900', 'T800', 'T440'],
  'Peterbilt': ['579', '389', '567', '348', '337'],
  'Mack': ['Anthem', 'Pinnacle', 'Granite', 'TerraPro'],
  'International': ['LT', 'RH', 'HX', 'HV', 'CV'],
  'Western Star': ['49X', '47X', '57X', '5700'],
  'Hino': ['700', '500', '300', '200'],
  'Sinotruk (HOWO)': ['A7', 'T7H', 'Sitrak C7H', 'T5G'],
  'Shacman': ['X3000', 'X5000', 'F3000', 'M3000'],
  'FAW Trucks': ['J6', 'J7', 'CA'],
  'Foton Trucks': ['Auman', 'Aumark'],
};

/** Lowercased TRUCK_MAKES keys, for fuel-type heuristics etc. */
export const HEAVY_TRUCK_BRANDS = new Set(Object.keys(TRUCK_MAKES).map((m) => m.toLowerCase()));

// Production year range per brand: [firstYear, lastYear] — lastYear is
// `null` for brands still in production. Only brands whose real range
// differs meaningfully from "recent decades" are listed here (discontinued
// marques, and newer marques that didn't exist before a certain year) —
// everything else falls back to the generic wide range in getYearsForMake,
// since guessing an exact founding year for every one of ~165 brands isn't
// something to get precise without a source, and the generic range is a
// safe default (never wrong in the "can't select this year" sense).
const BRAND_YEAR_RANGES: Record<string, [number, number | null]> = {
  // Discontinued car brands
  'Trabant': [1957, 1991],
  'Wartburg': [1956, 1991],
  'Zaporozhets': [1958, 1994],
  'Saab': [1949, 2012],
  'Pontiac': [1926, 2010],
  'Oldsmobile': [1897, 2004],
  'Mercury': [1938, 2011],
  'Plymouth': [1928, 2001],
  'Scion': [2003, 2016],
  'Saturn': [1985, 2010],
  'Daewoo': [1967, 2011],
  'Ravon': [2015, 2020],
  'TagAZ': [1998, 2014],
  'Rover': [1904, 2005],
  'Vauxhall': [1903, null],
  'Hummer': [1992, null], // H1-H3 ended 2010, revived as Hummer EV 2020
  // Brands that didn't exist before a certain year
  'Tesla': [2008, null],
  'Lucid': [2021, null],
  'Rivian': [2021, null],
  'NIO': [2018, null],
  'Polestar': [2017, null],
  'Zeekr': [2021, null],
  'VinFast': [2019, null],
  'XPeng': [2018, null],
  'Voyah': [2020, null],
  'Xiaomi': [2024, null],
  'Rimac': [2018, null],
  'Cupra': [2018, null],
  'DS': [2014, null],
  'Genesis': [2015, null],
  'Ora': [2018, null],
  'Lynk': [2017, null],
  // Discontinued heavy-truck brands
  'ZIL': [1924, 2014],
};

/** Descending year list for the given make, newest first — clamped to
 * that brand's actual production span instead of a one-size-fits-all range. */
export function getYearsForMake(make: string, currentYear: number): number[] {
  const range = BRAND_YEAR_RANGES[make];
  const earliest = currentYear - 64;
  const start = range ? Math.min(range[1] ?? currentYear, currentYear) : currentYear;
  const end = range ? Math.max(range[0], earliest) : earliest;
  const years: number[] = [];
  for (let y = start; y >= end; y--) years.push(y);
  return years;
}
